import Head from "next/head";
import { useState, useEffect } from "react";
import Layout, { UserContext } from "../components/layout";
import { User } from "../utils/user";
import Card from "../components/card";
import CardContainer from "../components/cardContainer";
import { useContext } from "react";
import { Pagination, Chip } from "@mui/material";
import { Movie, getMovie, getAllMovies } from "../utils/movie";
import CircularProgress from "@mui/material/CircularProgress";
import { Show, getAllShows } from "../utils/show";
const handleFilterDelete = () => {
  console.log("deleted Filter");
}

export default function Home() {
  const user: User = useContext(UserContext);
  const [loading, setLoading] = useState(0); // 0 - loading 1 - loaded 2 - error
  const [movies, setMovies] = useState<Movie[]>([]);
  const [shows, setShows] = useState<Show[]>([]);
  const [showingMovies, setShowingMovies] = useState<Movie[]>([]);
  useEffect(() => {
    getAllMovies().then((data) => {
      console.log("Data from getMovies", data);
      setMovies(data);
    }).catch((err) => {
      setLoading(2);
      console.log("Error from getMovies", err);
    });

    getAllShows().then((data) => {
      console.log("Data from getShows", data);
      setShows(data);
      setLoading(1);
    }).catch((err) => {
      setLoading(2);
      console.log("Error from getShows", err);
    });
  }, []);

  useEffect(() => {
    const showingMovies : Movie[] = [];
    movies.forEach((movie) => {
      if (shows.find((show) => show.movieID == movie.movieID)) {
        showingMovies.push(movie);
      }
    });
    setShowingMovies(showingMovies);
  }, [shows, movies]);
  console.log("User from in", user);
  return (
    <Layout>
      <Head>
        <title>E-Cinema</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col min-h-screen p-4">
        <h1 className="w-full text-center text-5xl md:text-[5rem] leading-normal font-extrabold text-text-dark">
          <span className="text-primary">E-Cinema</span> App
        </h1>
        <h2 className="text-text-light text-2xl leading-loose font-extrabold">Now Playing →</h2>
        <CardContainer>
          <div className="flex ">
            {
              loading === 0 ? <CircularProgress /> : loading === 1 ? showingMovies.map((movie) => {
                return (
                  <Card
                    key={movie.movieID}
                    movie={movie}
                  />
                );
              }) : <h1 className="text-text-light font-extrabold">There was an error loading the movies</h1>
            }
          </div>
        </CardContainer>
        <div className="flex items-center">
          <h2 className="text-text-light text-2xl leading-loose font-extrabold"> All Movies →</h2>

        </div>
        <CardContainer grid>
          <>
            {
              loading == 0 ? <CircularProgress /> // loading
                : loading == 1 ? // loaded
                movies?.map((movie) => (
                  <Card little key={movie.movieID} movie={movie} />
                )) 
                : // error 
                <h1 className="text-text-light font-extrabold">There was an error loading the movies</h1>
            }
          </>
        </CardContainer>
        <Pagination count={10} className='mx-auto mt-10' color="primary" />
      </main>
    </Layout>
  );
}

