import Head from "next/head";
import Layout, { UserContext } from "../components/layout";
import { User } from "../utils/user";
import Card from "../components/card";
import CardContainer from "../components/cardContainer";
import { useContext } from "react";
import { Pagination, Chip } from "@mui/material";
const handleFilterDelete = () => {
  console.log("deleted Filter");
}

export default function Home() {
  const user: User = useContext(UserContext);
  console.log("User from in",user);
  return (
    <Layout>
      <Head>
        <title>E-Cinema</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="container mx-auto flex flex-col min-h-screen p-4">
          <h1 className="w-full text-center text-5xl md:text-[5rem] leading-normal font-extrabold text-text-dark">
            <span className="text-primary">E-Cinema</span> App
          </h1>
          <h2 className="text-text-light text-2xl leading-loose font-extrabold">Trending →</h2>
          <CardContainer>
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
            <Card />
          </CardContainer>
          <div className="flex items-center">
            <h2 className="text-text-light text-2xl leading-loose font-extrabold"> All Movies →</h2>
            <Chip label="Filters will go here" color='primary' variant="outlined" onDelete={handleFilterDelete} className="ml-2" />
            <Chip label="Filter 2" color='primary' onDelete={handleFilterDelete} className="ml-2" />
          </div>
          <CardContainer grid>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
            <Card little></Card>
          </CardContainer>
          <Pagination count={10} className='mx-auto mt-10' color="primary" />
        </main>
    </Layout>
  );
}

