import React from 'react'
import Layout from '../components/layout'
import Head from 'next/head'

export default function userSettings() {
    return (
        <Layout>
            <Head>
                <title>E-Cinema</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto flex flex-col min-h-screen p-4">
                <h1 className="w-full text-center text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-600">
                    <span className="text-purple-300">User</span> Settings
                </h1>
            </main>
        </Layout>
    )
}
